---
injector:
  enabled: false
server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/issuer: "vault-issuer"
      cert-manager.io/common-name: "vault.immofficient.com"
    hosts:
      - host: vault.immofficient.com
        paths: []
  statefulSet:
    securityContext:
      container:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: "RuntimeDefault"
